version: '2'
services:
  web:
    build: ./website
    command: python -u main.py
    ports:
      - "12000:5000"
    volumes:
      - ./website:/code
    links:
      - api
  api:
    build: ./api
    command: python -u main.py
    expose:
      - "5000"
    ports:
      - "12100:5000"
    volumes:
      - ./api:/code
    links:
      - db
      - dummy-sensor
  db:
    image: mongo:3.4
    command: --smallfiles --rest
  dummy-sensor:
    build: ./dummy_sensor
    command: python -u main.py
    expose:
      - "5000"
    volumes:
      - ./dummy_sensor:/code